config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :songs do
    collection do 
      get 'next_song'
    end
    get 'add_to_playlist', on: :member
    post 'create_playlist_song', on: :member
  end

  delete 'playlists/:playlist_id/remove_song/:song_id', to: 'playlists#remove_from_playlist', as: :remove_from_playlist
  resources :albums
  resources :playlists
  resources :artists
  root 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/song.rb
class Song < ApplicationRecord
    has_one_attached :mp3
    has_one_attached :image
    belongs_to :user
    validates_presence_of :user
    has_many :playlist_songs
    has_many :playlists, through: :playlist_songs

    def self.search(query)
        where("LOWER(name) LIKE ?", "%#{query.downcase}%")
    end

end

app/controllers/songs_controller.rb
require 'mp3info'


class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]


  def add_to_playlist
    @song = Song.find(params[:id])
    @playlists = Playlist.where(user_id: current_user.id)
  end

  def create_playlist_song
    @song = Song.find(params[:id])
    selected_playlist_ids = Array(params[:song][:playlist_ids]).reject(&:empty?)
    
    if selected_playlist_ids.empty?
      redirect_to add_to_playlist_song_path(@song), alert: 'Please select at least one playlist.'
    else
      selected_playlist_ids.each do |playlist_id|
        playlist = Playlist.find(playlist_id)
        position = playlist.songs.count + 1
        playlist.playlist_songs.create(song: @song, position: position)
      end
    
      redirect_to @song, notice: 'Song added to playlist(s) successfully.'
    end
  end

  # GET /songs or /songs.json
  def index
    if params[:search]
      @songs = Song.search(params[:search])
    else
      @songs = Song.all
    end
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    #check if the current user 
    #add the current_user to the song
    if current_user.is_artist
      @song = Song.new(user_id: current_user.id)
    else
      redirect_to root_path, notice:"Only Artists can do that."
    end
  end

  def next_song
    if @playlist = Playlist.find(params[:playlist_id]) rescue nil
      @song = @playlist.songs.find(params[:song_id]) rescue nil
      @next_song = @playlist.songs.find_by('playlists_songs.position > ?', @song.playlist_songs.find_by(playlist: @playlist).position) rescue nil if @song
      unless @next_song
        @next_song = @playlist.songs_by_position.first
      end
    else
      @song = Song.find(params[:song_id]) rescue nil
      @next_song = Song.where.not(id: @song.id).sample
    end
    render json: @next_song
  end

  # GET /songs/1/edit
  def edit
    if current_user == @song.user
    else
      redirect_to songs_path, notice:"Only the owner can do that."
    end
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)


    if params[:song][:mp3].present?
      mp3_file = params[:song][:mp3].tempfile
      Mp3Info.open(mp3_file) do |mp3info|
        @song.length = mp3info.length
      end
    end

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if current_user == @song.user
        if @song.update(song_params)
          format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
          format.json { render :show, status: :ok, location: @song }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      else
        redirect_to root_path, notice:"Only Song creator can do that."
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    respond_to do |format|
      if current_user == @song.user
        @song.destroy
        format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to song_url, alert: "Only the owner can do that." }
        format.json { render json: { error: "Unauthorized" }, status: :unauthorized }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:name, :description, :length, :mp3, :image, :user_id, :album_id)
    end
end

app/helpers/songs_helper.rb
# app/helpers/songs_helper.rb

module SongsHelper
  def formatted_duration(seconds)
    minutes = seconds.to_i / 60
    remaining_seconds = seconds.to_i % 60
    "#{minutes}:#{format('%02d', remaining_seconds)}"
  end
end

app/views/songs/_form.html.erb
<%= form_with(model: song, class: "mt-4", local: true) do |form| %>
  <% if song.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter song name" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Enter song description" %>
  </div>

  <div class="form-group">
    <strong>Audio:</strong>
    <div class="custom-file">
      <%= form.file_field :mp3, id: 'audio-input', class: "custom-file-input", accept: 'audio/mpeg, audio/mp3' %>
      <%= form.label :mp3, class: "custom-file-label", data: { browse: "Browse" } %>
    </div>
  </div>

  <div class="form-group">
    <strong>Image:</strong>
    <div class="custom-file">
      <%= form.file_field :image, id: 'image-input', class: "custom-file-input", accept: "image/*" %>
      <%= form.label :image, class: "custom-file-label", data: { browse: "Browse" } %>
    </div>
  </div>

  <%= form.hidden_field :user_id, value: song.user_id %>

  <div class="form-group">
    <%= form.label :album_id %>
    <%= form.collection_select :album_id, Album.all, :id, :name, { prompt: "Select an album" }, class: "form-control" %>
  </div>

  <div class="text-center">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="mr-auto">
          <%= image_tag url_for(@song.image), class: "img-fluid-song", style:"width:32px !important; height:32px !important;" %>
          <%= @song.name %>, by
          <%= @song.user.full_name %>
        </div>
        <div class="ml-2 inline-buttons">
        <a href="#" class="song-link btn btn-outline-primary ml-2" data-song-id="<%= @song.id %>">
          <h5 class="card-title">Play</h5>
        </a>
        </div>
      </li>
</ul>

app/views/songs/add_to_playlist.html.erb
<%= form_for @song, url: create_playlist_song_song_path(@song), method: :post do |f| %>
  <div class="field">
    <%= f.label 'Select Playlist' %>
    <%= f.collection_select(:playlist_ids, @playlists, :id, :name, {}, { multiple: true, required: true }) %>
  </div>

  <div class="actions">
    <%= f.submit 'Add to Playlist' %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Show this song", @song %> |
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Songs</h1>

<div id="songs">
  <%= form_tag(songs_path, method: "get", class: "form-inline mb-2") do %>
    <div class="input-group">
      <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Search songs") %>
      <div class="input-group-append">
        <%= submit_tag("Search", class: "btn btn-outline-success") %>
      </div>
    </div>
  <% end %>

  <ul class="list-group">
    <% @songs.each do |song| %>
      <li id="<%= dom_id song %>" class="list-group-item mb-3" style="margin-bottom: auto !important;">
        <div class="row">
          <% if song.image.present? %>
            <div class="col-md-3">
              <%= image_tag url_for(song.image), class: "img-fluid-song" %>
            </div>
          <% end %>
          <% if song.name.present? %>
            <div class="col-md-6 d-flex flex-column justify-content-center">
              <h5><%= link_to song.name, song %></h5>
              <p><strong>Author:</strong> <%= song.user.full_name %></p>
            </div>
          <% end %>
          <div class="col-md-3 d-flex align-items-center justify-content-end">
            <h5 class="card-title song-link btn btn-outline-primary ml-2" data-song-id="<%= song.id %>" data-action="click->audio#playSong">Play</h5>
          </div>
        </div>
      </li>
    <% end %>
  </ul>


</div>

<% if current_user.is_artist %>
  <%= link_to "New song", new_song_path %>
<% end %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/show.html.erb
<p style="color: green"><%= notice %></p>


<ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="mr-auto">
          <%= image_tag url_for(@song.image), class: "img-fluid-song", style:"width:32px !important; height:32px !important;" %>
          <%= @song.name %>, by
          <%= @song.user.full_name %>
        </div>
        <div class="ml-2 inline-buttons">
        <h5 class="card-title song-link btn btn-outline-primary ml-2" data-song-id="<%= @song.id %>" data-action="click->audio#playSong">Play</h5>
        </div>
      </li>
</ul>

<div class="mt-3">
  <% if current_user == @song.user %>
    <%= link_to "Edit this song", edit_song_path(@song), class: "btn btn-secondary mr-2" %>
    <%= link_to "Back to songs", songs_path, class: "btn btn-secondary mr-2" %>
    <%= button_to "Destroy this song", @song, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>


<%= link_to 'Add to Playlist', add_to_playlist_song_path(@song) %>