config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :songs do
    collection do 
      get 'next_song'
    end
    get 'add_to_playlist', on: :member
    post 'create_playlist_song', on: :member
  end

  delete 'playlists/:playlist_id/remove_song/:song_id', to: 'playlists#remove_from_playlist', as: :remove_from_playlist
  resources :albums
  resources :playlists
  resources :artists
  root 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<% if current_user %>
<%= form_tag(root_path, method: "get", class: "form-inline mb-2") do %>
  <div class="input-group">
    <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Search songs, albums, and artists") %>
    <div class="input-group-append">
      <%= submit_tag("Search", class: "btn btn-outline-success") %>
    </div>
  </div>
<% end %>

<% if params[:search] %>
  <% if @search_results_available %>
    <h1>Search Results</h1>

    <% if @songs.present? %>
      <h2>Songs</h2>
      <ul>
        <% @songs.each do |song| %>
          <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div class="mr-auto">
                    <%= image_tag url_for(song.image), class: "img-fluid-song", style:"width:32px !important; height:32px !important;" %>
                    <%= song.name %>, by
                    <%= song.user.full_name %>
                  </div>
                  <div class="ml-2 inline-buttons">
                  <h5 class="card-title song-link btn btn-outline-primary ml-2"data-song-id="<%= song.id %>" data-action="click->audio#playSong">Play</h5>
                  </div>
                </li>
          </ul>
        <% end %>
      </ul>
    <% else %>
      <p>No songs available.</p>
    <% end %>

    <% if @albums.present? %>
      <h2>Albums</h2>
      <ul>
        <% @albums.each do |album| %>
          <li><%= link_to album.name, album_path(album) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No albums available.</p>
    <% end %>

    <% if @artists.present? %>
      <h2>Artists</h2>
      <ul>
        <% @artists.each do |user| %>
        <% if user.is_artist %>
          <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div class="mr-auto">
                    <% if user.avatar_url.present?%>
                      <%= image_tag url_for(user.avatar_url), class: "img-fluid-song", style:"width:32px !important; height:32px !important;" %>
                    <% else %>
                      <%= image_tag "https://i.pravatar.cc/32?u=#{user.full_name}", style:"height:32px; width:32px; border-radius:30%;" %>
                    <% end %>
                    <%= user.full_name %>
                  </div>
                  <div class="ml-2 inline-buttons">
                    <%= link_to "Show profile", artist_path(user), class:"btn btn-outline-primary ml-2" %>
                  </div>
                </li>
          </ul>
        <% end %>
      <% end %>
    <% else %>
      <p>No artists available.</p>
    <% end %>

  <% else %>
    <p>No results found for your search.</p>
  <% end %>

<% end %>

<% else %>
<%= render partial='layouts/navbar'%>
    <div class="join-now">
        <div class="join-now-info">
            <%= image_tag("Spotify_App_Logo.png", size: "96x96", style: "border-radius: 30%;") %>
            <br>
            <h1>Join now!</h1>
            <p>Listen to tons of songs for free</p>
            <p>Search for any song, artist, album or playlist</p>
            <p>Make your own playlists</p>
            <p>Easy to use, no extra fees required</p>

            <%= link_to 'Sign up', new_user_registration_path, class: 'home-sign-up' %>
        </div>
    </div>    

    <div class="picture-show">
        <%= image_tag("first.png") %>
        <%= image_tag("second.png") %>
        <%= image_tag("third.png") %>
        <%= image_tag("forth.png") %>
    </div>
<% end %>