config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :songs do
    collection do 
      get 'next_song'
    end
    get 'add_to_playlist', on: :member
    post 'create_playlist_song', on: :member
  end

  delete 'playlists/:playlist_id/remove_song/:song_id', to: 'playlists#remove_from_playlist', as: :remove_from_playlist
  resources :albums
  resources :playlists
  resources :artists
  root 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    belongs_to :user
    has_many :playlist_songs
    has_many :songs, through: :playlist_songs

    def songs_by_position
        self.songs.order('playlists_songs.position')
    end




    def self.ransackable_attributes(auth_object = nil)
        ["cover_image", "created_at", "id", "name", "privacy", "updated_at", "user_id"]
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.where(user_id: current_user.id)
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id
    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove_from_playlist
    @playlist = Playlist.find(params[:playlist_id])
    @song = Song.find(params[:song_id])

    # Find the position of the song being removed
    position_to_remove = @playlist.playlist_songs.find_by(song_id: @song.id).position

    # Remove the song from the playlist
    @playlist.songs.delete(@song)

    # Update the positions of the remaining songs
    @playlist.songs.where('playlists_songs.position > ?', position_to_remove).each do |song|
      current_position = song.playlist_songs.find_by(playlist: @playlist).position
      song.playlist_songs.find_by(playlist: @playlist).update(position: current_position - 1)
    end

    redirect_to playlist_path(@playlist), notice: 'Song removed from playlist successfully.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:name, :cover_image, :privacy)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, class: "mt-4") do |form| %>
  <% if playlist.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter playlist name" %>
  </div>

  <div class="text-center">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">

  <h2 class="mt-3"><%= playlist.name %></h2>

</div>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Show this playlist", @playlist %> |
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/index.html.erb
<div class="container mt-5">
  <p style="color: green;"><%= notice %></p>

  <h1 class="mb-4">Playlists</h1>

  <div id="playlists">
    <% @playlists.each do |playlist| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="mt-3"><%= playlist.name %></h5>
          <p class="card-text text-right"> <!-- Align the link to the right -->
            <%= link_to "Show this playlist", playlist, class: "btn btn-primary" %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "New playlist", new_playlist_path, class: "btn btn-success" %>
</div>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/show.html.erb
<div class="container mt-5">
  <p class="text-success"><%= notice %></p>

  <%= render @playlist %>

  <h5 class="card-title song-link btn btn-outline-primary ml-2" data-playlist-id="<%= @playlist.id %>" data-song-id="<%= @playlist.songs_by_position.first.try(:id) %>" data-action="click->audio#playSong">Play</h5>
  <h4 class="mt-3">Songs in Playlist:</h4>
  <ul class="list-group">
    <% @playlist.songs.each do |song| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="mr-auto">
          <%= image_tag url_for(song.image), class: "img-fluid-song", style:"width:32px !important; height:32px !important;" %>
          <%= song.name %>
        </div>
        <div class="ml-2 inline-buttons">
          <%= button_to 'Remove', remove_from_playlist_path(playlist_id: @playlist.id, song_id: song.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <h5 class="card-title song-link btn btn-outline-primary ml-2" data-playlist-id="<%= @playlist.id %>" data-song-id="<%= song.id %>" data-action="click->audio#playSong">Play</h5>
        </div>
      </li>
    <% end %>
  </ul>


  <div class="mt-3">
    <%= link_to "Edit this playlist", edit_playlist_path(@playlist), class: "btn btn-warning mr-2" %>
    <br>
    <%= link_to "Back to playlists", playlists_path, class: "btn btn-secondary mr-2" %>
    <br>
    <%= button_to "Destroy this playlist", @playlist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>