config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :songs do
    collection do 
      get 'next_song'
    end
    get 'add_to_playlist', on: :member
    post 'create_playlist_song', on: :member
  end

  delete 'playlists/:playlist_id/remove_song/:song_id', to: 'playlists#remove_from_playlist', as: :remove_from_playlist
  resources :albums
  resources :playlists
  resources :artists
  root 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="fixed-bottom">
       <div class="row justify-content-center mt-0 pt-0 row-1 mb-0  px-sm-3 px-2">
            <div class="col-12">
                <div class="row my-4 row-1 no-gutters">
                    <div class="col-sm-3 col-auto text-center"><small>&#9400; OSTips Software, 2023</small></div><div class="col-md-3 col-auto "></div><div class="col-md-3 col-auto"></div>
                    <div class="col  my-auto text-md-left  text-right "> <small>fejk@mejl.com</div> 
                </div>
            </div>
        </div>
    </footer>
  </div>
  

app/views/layouts/_homepage.html.erb
<% if current_user %>
<%= form_tag(@home_path, method: "get", class: "form-inline mb-2") do %>
  <div class="input-group">
    <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Search songs, albums, and artists") %>
    <div class="input-group-append">
      <%= submit_tag("Search", class: "btn btn-outline-success") %>
    </div>
  </div>
<% end %>

<% if params[:search] %>
  <% if @search_results_available %>
    <h1>Search Results</h1>

    <% if @songs.present? %>
      <h2>Songs</h2>
      <ul>
        <% @songs.each do |song| %>
          <li><%= link_to song.name, song_path(song) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No songs available.</p>
    <% end %>

    <% if @albums.present? %>
      <h2>Albums</h2>
      <ul>
        <% @albums.each do |album| %>
          <li><%= link_to album.name, album_path(album) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No albums available.</p>
    <% end %>

    <% if @artists.present? %>
      <h2>Artists</h2>
      <ul>
        <% @artists.each do |user| %>
        <% if user.is_artist %>
          <li><%= link_to user.full_name, user_path(user) %></li>
        <% end %>
      <% end %>
    <% else %>
      <p>No artists available.</p>
    <% end %>

  <% else %>
    <p>No results found for your search.</p>
  <% end %>

<% end %>

<% else %>
<%= render partial='layouts/navbar'%>
    <div class="join-now">
        <div class="join-now-info">
            <%= image_tag("Spotify_App_Logo.png", size: "96x96", style: "border-radius: 30%;") %>
            <br>
            <h1>Join now!</h1>
            <p>Listen to tons of songs for free</p>
            <p>Search for any song, artist, album or playlist</p>
            <p>Make your own playlists</p>
            <p>Easy to use, no extra fees required</p><% if params[:search] %>
  <% if @search_results_available %>
    <h1>Search Results</h1>

    <h2>Songs</h2>
    <ul>
      <% @songs.each do |song| %>
        <p>HEHE<p>
        <li><%= link_to song.name, song_path(song) %></li>
      <% end %>
    </ul>

    <h2>Albums</h2>
    <ul>
      <% @albums.each do |album| %>
        <li><%= link_to album.name, album_path(album) %></li>
      <% end %>
    </ul>

    <h2>Artists</h2>
    <ul>
      <% @artists.each do |artist| %>
        <% if artist.user.isArtist %>
          <li><%= link_to artist.name, user_path(artist.user) %></li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <p>No results found for your search.</p>
  <% end %>
<% else %>
  <%= form_tag(home_path, method: "get", class: "form-inline mb-2") do %>
    <%= text_field_tag(:search, params[:search], class: "form-control mr-sm-2", placeholder: "Search songs, albums, and artists") %>
    <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0") %>
  <% end %>
<% end %>

            <%= link_to 'Sign up', new_user_registration_path, class: 'home-sign-up' %>
        </div>
    </div>    

    <div class="picture-show">
        <%= image_tag("first.png") %>
        <%= image_tag("second.png") %>
        <%= image_tag("third.png") %>
        <%= image_tag("forth.png") %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"> <!-- Use navbar-dark and bg-dark for dark theme -->
    <div class="container">
      <a class="navbar-brand" href="/">
        <%= image_tag("Spotify_App_Logo.png", size: "32x32", style: "border-radius: 30%;") %>
      </a>
      <a class="navbar-brand" href="/">
        <h3>Spoti-fejk</h3>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <% if current_user %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/songs">Songs</a>
          </li>
            <li class="nav-item">
              <%= link_to "My playlists", playlists_path, class: "nav-link active", style:"margin-right:8px;" %>
            </li>
            <li class="nav-item">
              <%= link_to "Albums", albums_path, class: "nav-link active", style:"margin-right:8px;" %>
            </li>
            <% if current_user.is_admin? %>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
              </li>
            <% end %>
          </ul>
          <% if current_user.avatar_url.present?%>
              <%= image_tag current_user.avatar_url, style:"height:32px; width:32px; border-radius:30%;" %>
          <% else %>
              <%= image_tag "https://i.pravatar.cc/32?u=#{current_user.full_name}", style:"height:32px; width:32px; border-radius:30%;" %>
          <% end %>
          
          <form class="">
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-outline-primary mr-2" %>
            </li>
          </form>
          <% else %>
            <form class="form-inline ml-auto">
              <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary mr-2", style:"margin-right:8px;" %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary mr-2" %>
            </form>
          <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotiFejk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="audio">
  
    <% if user_signed_in? %>
    <!-- Include your audio player component -->
    <%= render partial='layouts/navbar'%>
    <div class="main-content-container">
        <main class="container main-content">
          <%= yield %>
        </main>
    </div>
    <div class="footer-player" >
      <span id="current-song-name"></span>
      <a href="#" id="play-prev-song" data-action="audio#playPreviousSong">Prev</a>
      <a href="#" id="play-next-song" data-action="audio#playNextSong">Next</a>
      <br>
      <a href="#" data-audio-target="songName" >Nič se ne predvaja</a>
      <a href="#" data-audio-target="songAuthor" ></a>
      <br>
      <audio controls id="audio-player" data-audio-target="audioPlayer"></audio>
    </div>
    <% else %>
      <%= yield %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>